---
version: '3.9'
services:
  service-a:
    build: ./service-a
    ports:
      - "8080:8080"

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"

  service-a-prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/service-a-prometheus.yaml:/etc/prometheus/prometheus.yaml"

  service-b-prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - "9091:9091"
    volumes:
      - "./prometheus/service-b-prometheus.yaml:/etc/prometheus/prometheus.yaml"